.TH TM-MANAGER 1 "2026-02-15" "Daniel Nylander" "TM Manager Manual"
.SH NAME
tm-manager - Translation Memory Manager for TMX files
.SH SYNOPSIS
.B tm-manager
.SH DESCRIPTION
\fBtm-manager\fR is a GTK4/Adwaita application for managing TMX translation memory files. Features include opening and creating TMX files, fuzzy search, importing from .po/.ts/.xliff, exporting to other formats, statistics display, filtering by language/project/date, segment editing, and TMX merging.
.SH OPTIONS
.TP
.B \-\-help
Show help message and exit.
.SH FILES
.TP
.I ~/.config/tm-manager/
Configuration files.
.TP
.I ~/.cache/tm-manager/
Cached data.
.SH BUGS
Report bugs at https://github.com/yeager/tm-manager/issues
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
.SH SEE ALSO
Project homepage: https://github.com/yeager/tm-manager
